### ISSUE TITLE
Elven forge aspects is set twice

### ISSUE THREAD

**Issue by DwarfyAssassin** [SOL3675/MiddleEarth-Thaumaturgy#5]
The aspects of the elven forge is set twice. Once with earth, fire and elven and a bit further down th list with earth, fire and tool. 

It's nothing urgent but just something I noticed.
Also if you want any help with the mod I would be glad to help even if progress is kinda paused.

**Comment by SOL3675** [comment]
Thank you for your report. Second one should be Alloy Forge.
Fixed in dev.
