### ISSUE TITLE
Handheld Factions Crafter does not work again,in 0.7.1,singleplayer

### ISSUE THREAD

**Issue by Twilight2** [SOL3675/MiddleEarth-Thaumaturgy#7]
I only have the lotrmod,baubles,thaumcraft,this mod,four mods installed,and even after used the command to give me all researches(/thaumcraft research player alll),but it still doesn't work.

**Comment by SOL3675** [comment]
I can't reproducible in my environment.
I need more info like forge version, java version, logs and others.

**Comment by Twilight2** [comment]
forge：1614，java：java8 update211 64-bit

**Comment by Twilight2** [comment]
Dosen't works in server，too

**Comment by SOL3675** [comment]
I have no time to fix this recently.
Try lotr mod v35.3 if you want to use this.

**Comment by Twilight2** [comment]
ok，thanks.It still a good container of these crafting tables

**Comment by SOL3675** [comment]
lotr mod v35.4 has method for presence for the table.
I'll add gui on this mod's instance and get more extensibility.

**Comment by SOL3675** [comment]
![2020-01-12_14 32 46](https://user-images.githubusercontent.com/16431933/72214581-8136ef80-3548-11ea-9ebe-c0e0f390312d.png)
